#   _
#  / \
# | o |    lukejans
# |   |  starship.toml
#  ^^^

add_newline = false

format = """
$directory\
$character\
"""

right_format = """
$all
"""

command_timeout = 1000

[directory]
truncation_length = 1

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[✘](bold red)'

[nodejs]
symbol = '⬢ '

[git_branch]
symbol = " "
